security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api
            stateless: true
            access_token:
                token_handler: sgoranov\PHPIdentityLinkShared\Security\AccessTokenHandler


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/api/v1/auth, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/api, roles: ROLE_ADMIN }

