version: '3.5'
services:

  db-users:
    container_name: db-users
    privileged: true
    build:
      context: ${IDENTITY_LINK_DB_USERS_SOURCE_DIR}
    ports:
      - 9001:80
    volumes:
      - ${IDENTITY_LINK_DB_USERS_SOURCE_DIR}:/var/www
    environment:
      PGHOST: database-server
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
    extra_hosts:
      - host.docker.internal:${HOST_GW:-host-gateway}
    depends_on:
      - database-server
    networks:
      - my-network

  database-server:
    container_name: database-server
    image: postgres:15
    restart: always
    ports:
      - "9006:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - "9008:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "9007:8081"
    depends_on:
      - redis

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database-server
    ports:
      - 9005:8080
    networks:
      - my-network

  smtp-server:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 9025:1025 # smtp server
      - 9026:8025 # web ui
    networks:
      - my-network

networks:
  my-network:
    driver: bridge