services:

  identity-link-db-users-test:
    container_name: identity-link-db-users-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: identity-link-db-users-test
    environment:
      APP_SECRET: test
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      identity-link-database-server-test:
        condition: service_healthy
    networks:
      - identity-link-network

  identity-link-db-users-test-debug:
    extends:
      file: docker-compose-test.yaml
      service: identity-link-db-users-test
    container_name: identity-link-db-users-test-debug
    volumes:
      - .:/app
    entrypoint: bash
    stdin_open: true
    tty: true

  identity-link-database-server-test:
    container_name: identity-link-database-server-test
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: identity-link-db-users
    networks:
      - identity-link-network

networks:
  identity-link-network:
    driver: bridge