controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v1_ping:
    path: /api/v1/ping
    methods: GET
    controller: sgoranov\IdentityLinkShared\Controller\PingController::ping

api_v1_query:
    path: /api/v1/query
    methods: POST
    controller: sgoranov\IdentityLinkShared\Controller\QueryController::query